apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "api.fullname" . }}-secrets-crd
  namespace: {{ .Values.namespace.api.name }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "api.fullname" . }}-secrets
      type: Opaque
      data:
        - objectName: az-svc-bus-connection-string
          key: AZ_SVC_BUS_CONNECTION_STRING

        - objectName: az-cosmosdb-uri
          key: SPRING_AZURE_COSMOS_URI
        
        - objectName: az-cosmosdb-database
          key: SPRING_AZURE_COSMOS_DATABASE

        - objectName: az-cosmosdb-key
          key: SPRING_AZURE_COSMOS_KEY
        
        - objectName: az-storage-connection-string
          key: AZURE_BLOB_STORAGE_CONNECTION_STRING

        - objectName: az-storage-video-container-name
          key: AZURE_BLOB_STORAGE_VIDEO_CONTAINER_NAME

        - objectName: az-storage-image-container-name
          key: AZURE_BLOB_STORAGE_IMAGE_CONTAINER_NAME
      
  parameters:
    usePodIdentity: "false"
    # https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#limitations
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secrets.azureKeyVault.clientID }}
    keyvaultName: {{ .Values.secrets.azureKeyVault.keyVaultName }}
    tenantId: {{ .Values.secrets.azureKeyVault.tenantId }}
    objects: |
      array:
        - |
            objectName: az-svc-bus-connection-string
            objectType: secret
        - |
            objectName: az-cosmosdb-uri
            objectType: secret
        - |
            objectName: az-cosmosdb-database
            objectType: secret
        - |
            objectName: az-cosmosdb-key
            objectType: secret  
        - |
            objectName: az-storage-connection-string
            objectType: secret
        - |
            objectName: az-storage-video-container-name
            objectType: secret
        - |
            objectName: az-storage-image-container-name
            objectType: secret