apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api.fullname" . }}-ingress
  namespace: {{ .Values.namespace.api.name }}
  labels:
    app: {{ include "api.name" . }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "true"
    appgw.ingress.kubernetes.io/health-probe-path: {{ .Values.api.probe.path.readiness | quote }}
    appgw.ingress.kubernetes.io/health-probe-port: {{ .Values.api.ports.port | quote }}
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"

spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}

  rules:
  - host: {{ (index .Values.ingress.hosts 0).host | quote }}
    http:
      paths:
      - path: {{ .Values.api.ingress.path }}/*
        pathType: {{ .Values.api.ingress.pathType }}
        backend:
          service:
            name: {{ printf "%s-service" (include "api.fullname" .) }}
            port:
              number: {{ .Values.api.ports.port }}
      - path: {{ .Values.api.ingress.path }}
        pathType: {{ .Values.api.ingress.pathType }}
        backend:
          service:
            name: {{ printf "%s-service" (include "api.fullname" .) }}
            port:
              number: {{ .Values.api.ports.port }}
