apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-config
  labels:
    app: {{ include "api.name" . }}
  namespace: {{ .Values.namespace.api.name }}
data:
  SERVER_ADDRESS: {{ .Values.api.server.address | quote }}
  SERVER_PORT: {{ .Values.api.server.port | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.api.server.profilesActive | quote }}
  WEBSOCKET_BASE_ENDPOINT: {{ .Values.api.websocket.baseEndpoint | quote }}
  OTEL_GRPC_ENDPOINT: "http://videocore-otel-nr-otel-collector-nr-otel-collector.{{ .Values.namespace.monitor.name }}.svc.cluster.local:4317"
