namespace:
  api:
    name: replaced
  monitor:
    name: replaced

ingress:
  hosts:
    - host: "replaced"
  tls: []

api:
  name: reports

  replicaCount: 2

  image:
    repository: "replaced"
    tag: "replaced"

  ports:
    port: 9090
    name: http
  
  cors:
    allowedOrigins: "replaced"

  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi

  ingress:
    path: "replaced"
    pathType: Prefix

  probe:
    path:
      startup: /actuator/health
      liveness: /actuator/health/liveness
      readiness: /actuator/health/readiness

  server:
    address: 0.0.0.0
    port: 9090
    profilesActive: "prod"

  hpa:
    minReplicas: 1
    maxReplicas: 2
    cpu:
      utilization:
        averageUtilization: 70

  websocket:
    baseEndpoint: "replaced"

secrets:
  azureKeyVault:
    keyVaultName: "replaced"
    tenantId: "replaced"
    clientID: "replaced"