server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8085}
  servlet:
    context-path: /

spring:
  cloud:
    azure:
      # Mensageria
      # https://github.com/Azure/azure-sdk-for-java/issues/43106
      servicebus:
        connection-string: ${AZ_SVC_BUS_CONNECTION_STRING:Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;}
      cosmos:
        enabled: false
# Observabilidade
otel:
  instrumentation:
    micrometer:
      enabled: false
  sdk:
    disabled: true

# WebSocket
websocket:
  base-endpoint: ${WEBSOCKET_BASE_ENDPOINT:/ws}