server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8085}
  servlet:
    context-path: /

azure:
  service-bus:
    connection-string: ${AZ_SVC_BUS_CONNECTION_STRING:Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;}

otel:
  instrumentation:
    micrometer:
      enabled: false
  sdk:
    disabled: true

websocket:
  base-endpoint: ${WEBSOCKET_BASE_ENDPOINT:/ws}

http:
  cors:
    allowed-origins: ${HTTP_CORS_ALLOWED_ORIGINS:*}